_target_: src.models.IPSModel
config:
  _target_: src.models.IPSConfig
  features: ???
  dims: 32
  layers: 3
  dropout: 0.1
  clip: 0.1
  positions: 50
  propensity_path: ${hydra:runtime.cwd}/propensities/global_all_pairs.csv
  loss_fn:
    _target_: src.loss.pointwise_sigmoid_ips_rax
    _partial_: True
