_target_: src.models.NaiveModel
config:
  _target_: src.models.NaiveConfig
  features: ???
  dims: 32
  layers: 3
  dropout: 0.1
  loss_fn:
    _target_: rax.pairwise_logistic_loss
    _partial_: True
    lambdaweight_fn:
      _target_: rax.dcg_lambdaweight
      _partial_: True
