name: ultr-reproducibility
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - charset-normalizer=3.3.2
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89ı
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gds-tools=1.4.0.31
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.4
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libsqlite=3.44.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - nsight-compute=2022.3.0.22
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.4
  - pillow=9.4.0
  - pip=23.3.1
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sympy=1.12
  - tbb=2021.10.0
  - tk=8.6.13
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - typing_extensions=4.8.0
  - urllib3=2.0.7
  - wheel=0.41.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - certifi==2023.7.22
      - chex==0.1.84
      - cloudpickle==3.0.0
      - datasets==2.14.6
      - dill==0.3.7
      - etils==1.5.2
      - flax==0.7.5
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - huggingface-hub==0.18.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - hydra-optuna-sweeper==1.3.0.dev0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - jax==0.4.20
      - jaxlib==0.4.20+cuda11.cudnn86
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.1
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nest-asyncio==1.5.8
      - numpy==1.26.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvcc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.9.6.50
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.19.3
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - optax==0.1.7
      - orbax-checkpoint==0.4.2
      - packaging==23.2
      - pandas==2.1.2
      - protobuf==4.25.0
      - pyarrow==14.0.0
      - pygments==2.16.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - rax==0.3.0
      - rich==13.6.0
      - scipy==1.11.3
      - six==1.16.0
      - submitit==1.5.0
      - tensorstore==0.1.47
      - toolz==0.12.0
      - tqdm==4.66.1
      - tzdata==2023.3
      - xxhash==3.4.1
      - yarl==1.9.2
      - zipp==3.17.0
