# @package _global_

# File to add best hyperparameters per model-loss combination:

#trainer:
#  learning_rate: 0.009560730093223512
#
#model:
#  relevance_dims: 512
#  relevance_layers: 1
#  relevance_dropout: 0.5
