# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    study_name: ???
    direction: maximize
    n_trials: 100
    n_jobs: 1
    max_failure_rate: 0.0
