# @package _global_

defaults:
  - base
  - override /model: naive

hydra:
  sweeper:
    study_name: naive
    params:
      trainer.learning_rate: tag(log, interval(0.00001, 0.1))
      model.relevance_dims: choice(16, 32, 64, 128, 256, 512, 1024)
      model.relevance_layers: range(0, 6)
      model.relevance_dropout: range(0.0, 1.0, step=0.1)
