# @package _global_

defaults:
  - base
  - override /model: naive

hydra:
  sweeper:
    search_space:
      hyperparameters:
        lr:
          type: uniform_float
          lower: 0.00001
          upper: 0.1
          log: True
        model.relevance_dims:
          type: uniform_int
          lower: 16
          upper: 1024
          log: True
        model.relevance_layers:
          type: uniform_int
          lower: 1
          upper: 6
        model.relevance_dropout:
          type: uniform_float
          lower: 0.0
          upper: 0.5
