# @package _global_

defaults:
  - base
  - override /model: pbm

hydra:
  sweeper:
    study_name: pbm
    params:
      trainer.learning_rate: tag(log, interval(0.00001, 0.1))
      model.relevance_dims: choice(16, 32, 64, 128, 256, 512, 1024)
      model.relevance_layers: range(1, 6)
      model.relevance_dropout: range(0.0, 0.5, step=0.1)
      model.bias_dims: choice(16, 32, 64, 128, 256, 512, 1024)
      model.bias_layers: range(1, 6)
      model.bias_dropout: range(0.0, 0.5, step=0.1)
