defaults:
  - _self_
  - model: two-towers
  - loss: listwise
  - user_const

random_state: 381

trainer:
  learning_rate: 0.0001
  epochs: 50
  patience: 3

hydra:
  job:
    chdir: True
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname}
