defaults:
  - _self_
  - data: baidu
  - model: dla
#  - hyperparameter: ${data}_${model}
  - user_const

random_state: 381
batch_size: 256
lr: 0.0001
max_epochs: 25
es_patience: 3

hydra:
  job:
    chdir: True
  sweep:
    dir: ${run_dir}
    subdir: ${hydra.job.override_dirname}
