defaults:
  - _self_
  - model: two-towers
  - loss: listwise
  - user_const

random_state: 381
batch_size: 256
lr: 0.00001

hydra:
  job:
    chdir: True
  sweep:
    dir: ${run_dir}
    subdir: ${hydra.job.override_dirname}
