defaults:
  - _self_
  - model: two-towers
  - loss: pointwise
  - user_const

random_state: 381
batch_size: 256
lr: 0.0001
max_epochs: 25
es_metric: dcg@10
es_patience: 4

hydra:
  job:
    chdir: True
  sweep:
    dir: ${run_dir}
    subdir: ${hydra.job.override_dirname}
