defaults:
  - _self_
  - model: two-towers
  - loss: pointwise
  - user_const

random_state: 381

trainer:
  learning_rate: 0.0001
  epochs: 50
  patience: 3
  val_metric: ndcg@10

hydra:
  job:
    chdir: True
  sweep:
    dir: multirun
