defaults:
  - _self_
  - model: two-towers
  - loss: listwise
  - user_const

random_state: 381
val_test_split: [0.5, 0.5]

hydra:
  job:
    chdir: True
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname}
