defaults:
  - _self_
  - data: tencent
  - user_const

random_state: 381
pca_dim: 15
kde_kernel: "gaussian"
kde_bw: 0.5


hydra:
  job:
    chdir: True
  sweep:
    dir: ${run_dir}
    subdir: ${hydra.job.override_dirname}
