cache_dir: /projects/0/prjs0860/huggingface
run_dir: multirun
num_workers: 6
num_jobs: 8
wandb_project_name: baidu-reproducibility
wandb_entity: cm-offline-metrics
logging: True
checkpoints: True
progress_bar: True
