# @package _global_
cluster:
  _target_: dask_jobqueue.SLURMCluster
  queue: gpu
  memory: 32GB
  cores: 8
  walltime: 2:00:00
  processes: 1
  nanny: False
  n_workers: ${hydra.sweeper.scenario.n_workers}
  job_extra_directives: ['--gres gpu:pascal:1']
  log_directory: tmp/smac_dask_slurm
