# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 180
    nodes: 1
    mem_gb: 32
    cpus_per_task: 8
    array_parallelism: "${num_jobs}"
    partition: gpu
    gres: gpu:pascal:1
