# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    nodes: 1
    mem_gb: 32
    cpus_per_task: 4
    array_parallelism: 8
    partition: gpu
    gres: gpu:1
