# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    nodes: 1
    array_parallelism: 4
    mem_gb: 64
    cpus_per_task: 16
    partition: gpu
    gres: gpu:1
    time: 12:00:00
